### ISSUE TITLE
I met a problem, I am looking forward to your reply.

### ISSUE THREAD

**Issue by qinger753** [yinzixuan126/mpc_path_follower_ros#1]
when I executed the second step:sudo apt-get install remmina synaptic gimp git ros-kinetic-navigation* ros-kinetic-gmapping ros-kinetic-ackermann-msgs ros-kinetic-turtlebot*-y
the errors appeared:注意，根据Glob 'ros-kinetic-navigation*' 选中了 'ros-kinetic-navigation'
注意，根据Glob 'ros-kinetic-navigation*' 选中了 'ros-kinetic-navigation-stage'
注意，根据Glob 'ros-kinetic-navigation*' 选中了 'ros-kinetic-navigation-tutorials'
注意，根据Glob 'ros-kinetic-navigation*' 选中了 'ros-kinetic-navigation-experimental'
注意，根据Glob 'ros-kinetic-navigation*' 选中了 'ros-kinetic-navigation-layers'
E: 无法定位软件包 ros-kinetic-turtlebot*-y
E: 无法按照 glob ‘ros-kinetic-turtlebot*-y’ 找到任何软件包
E: 无法按照正则表达式 ros-kinetic-turtlebot*-y 找到任何软件包

**Comment by yinzixuan126** [comment]
Firstly, make sure that you install ROS rightly. And then remove "ros-kinetic-turtlebot-y* " from the above commands so that you can install other packages.  Finally, try the following link to install turtlebot packages.
http://wiki.ros.org/turtlebot/Tutorials/indigo/Turtlebot%20Installation

**Comment by Curiosi-Orch** [comment]
there should be a space between turtlebot* and -y
