### ISSUE TITLE
when i add it as a local planner in move_base

### ISSUE THREAD

**Issue by longjianquan** [yinzixuan126/mpc_path_follower_ros#2]
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

cppad-20160000.1 error from a known source:
yq = f.Forward(q, xq): a zero order Taylor coefficient is nan.
Corresponding independent variables vector was written to binary a file.
vector_size = 158
file_name = /tmp/fileEuPtGw
index = 0

Error detected by false result for
    if( CppAD::isnan( yq[ (q+1) * index + 0 ] )
at line 224 in the file 
    /usr/include/cppad/local/forward.hpp
move_base: /usr/include/cppad/utility/error_handler.hpp:207: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.

how to sovle it?

**Comment by yinzixuan126** [comment]
It seems something is wrong with Ipopt's inputs. So, please replace mpc_path_follower with ROS builtin local planner (dwa_local_planer) to make sure that your robot works well then try mpc path follower again.

**Comment by longjianquan** [comment]
i find this bug.your code did not subscribe the topic "odom",so it did not get the data.i suceess after add "odom" topic .

**Comment by yinzixuan126** [comment]
if you
